---
- name: API Sever
  hosts: buildserver
  become: true

  pre_tasks:
    - name: Set a hostname
      ansible.builtin.hostname:
        name: "{{ project_name }}-api"

    - name: Update apt packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
        cache_valid_time: 3600
      when: ansible_facts['os_family'] == "Debian"

    - name: Install needed tools
      ansible.builtin.apt:
        name:
          - vim
          - nano
          - tmux
          - mysql-client
        state: present
      when: ansible_facts['os_family'] == "Debian"
  roles:
    - mysql
    - redis    