---
- name: Install MySQL and Redis
  hosts: localhost
  become: yes  # Run tasks as a superuser

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'  # Adjust for other distributions

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install Redis
      apt:
        name: redis-server
        state: present
      when: ansible_distribution == 'Ubuntu'